#!/bin/sh

echo "Running pre-commit checks..."

cd src/matching-api/

if ! command -v dotnet-script >/dev/null @>&1; then
  dotnet tool install -g dotnet-script
fi

dotnet script AlgorithmVersionBuild.csx

git add Algorithm/version.json

if [ $? -ne 0 ]; then
  echo "Pre-commit hook failed."
  exit 1
fi