version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: 'daily'
    labels:
      - github-actions
      - dependabot
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semvar-patch-days: 2
      
