query PersonByCriteria($maxAge: Int, $paging: RequestCursorInput) {
    personByCriteria(maxAge: $maxAge, paging: $paging) {
        cursor {
            offset
            pageNumber
            pageSize
            returned
            totalSize
        },
        results {
            ... on Person {
                age
                addresses {
                    id
                    preferred
                    location {
                        primaryNameOrNumber
                        street
                        town
                        postcode
                    }
                }
                dateOfBirth {
                    lower
                    upper
                    mask
                }
                id
                objectVersion
                personTypes
                forename
                surname
                gender
                ethnicity
                countryOfBirth
                nhsNumber
                preferredAddress {
                    id
                }
                worklistInstances {
                    worklistDefinition {
                        id
                    }
                }
                chronology {
                    chronologyEntries {
                        entryType
                    }
                }
            }
        }
    }
}