name: CI for SUI_Matcher

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Format code
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: 21

      - name: Install SonarCloud Scanner
        shell: bash
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install dotnet-reportgenerator-globaltool
        run: dotnet tool install --global dotnet-coverage

      - name: Start SonarCloud scanner
        run: |
          dotnet-sonarscanner begin \
          /k:"DFE-Digital_SUI_Matcher" \
          /o:"dfe-digital" \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage/coverage.xml \
          /d:sonar.coverage.exclusions=**/Program.cs,**/*.json \
          /d:sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S6602 \
          /d:sonar.scanner.scanAll=false \
          /d:sonar.cs.cobertura.reportPaths=coverage/coverage.xml

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: |
          dotnet test --no-build --settings tests.runsettings --results-directory ./coverage
          dotnet coverage merge --reports "coverage/**/coverage.cobertura.xml" -f cobertura -o coverage/coverage.xml

      - name: End SonarCloud scanner
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Publish coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/coverage.xml
          badge: true
          format: markdown
          hide_complexity: true
          output: both
      
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md