name: CI for SUI_Matcher

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
      
      - name: Install dotnet-reportgenerator-globaltool
        run: dotnet tool install --global dotnet-coverage

      - name: Test
        run: |
          dotnet test --no-build --settings tests.runsettings --results-directory ./coverage
          dotnet coverage merge --reports "coverage/**/coverage.cobertura.xml" -f cobertura -o coverage/coverage.xml


      - name: Publish coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/coverage.xml
          badge: true
          format: markdown
          hide_complexity: true
          output: both
      
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md