name: Deploy Client Infrastructure

on:
    push:
        branches:
        - main
        paths:
          - 'src/app-host/infra/**'
    workflow_dispatch:
        inputs:
            environment:
                description: 'Deployment environment'
                required: true
                default: 'Integration'
            what_if:
              description: Run bicep what-if to check for changes
              default: true
              type: boolean
            version:
                description: 'Deployment version'
                required: false
 
permissions:
  id-token: write
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        env: 
            AZURE_ENV_NAME: ${{ inputs.environment }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            AZURE_LOCATION: "westeurope"
            AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
            CLIENT_VERSION: ${{ inputs.version }}
            VM_USERNAME: ${{ secrets.VM_USERNAME }}
            VM_PASSWORD: ${{ secrets.VM_PASSWORD }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: 'Get latest tag if no version provided'
          id: get_latest_tag
          run: |
            if [[ -z "${{ env.CLIENT_VERSION }}" ]]; then
              LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
              echo "Latest tag is: $LATEST_TAG"
              echo "version=$LATEST_TAG" >> $GITHUB_ENV
            else
              echo "version=${{ env.CLIENT_VERSION }}" >> $GITHUB_ENV
            fi

        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            ref: ${{ env.version }}
            
        - name: Ensure Azure CLI is installed
          run: |
            if ! command -v az &> /dev/null; then
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            fi

        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ env.AZURE_CLIENT_ID }}
            tenant-id: ${{ env.AZURE_TENANT_ID }}
            subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
            
        - name: Run Bicep What-If
          if: ${{ inputs.what_if == true }}
          uses: Azure/deployment-what-if-action@v1.0.0
          with:
            subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
            resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
            templateFile: src/tools/client/SUI.Client.Watcher/infra/client.bicep
            additionalParameters: adminUsername="${{ env.VM_USERNAME }}" adminPassword="${{ env.VM_PASSWORD }}"

        - name: Deploy Bicep files for client environment
          if: ${{ inputs.what_if == false }}
          run: |
            az deployment group create \
                --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                --template-file src/tools/client/SUI.Client.Watcher/infra/client.bicep \
                --parameters adminUsername="${{ env.VM_USERNAME }}" adminPassword="${{ env.VM_PASSWORD }}" \