name: Build and Upload .NET Console App

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version number'
                required: true
                default: 'v0.0.14'
            blob_storage_location:
                description: 'Blob storage location'
                required: true
            environment:
                description: 'Environment'
                required: true
                default: 'Integration'
jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            AZURE_ENV_NAME: ${{ inputs.environment }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            AZURE_LOCATION: "westeurope"
            AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
            CLIENT_VERSION: ${{ inputs.version }}
            BLOB_STORAGE_LOCATION: ${{ inputs.blob_storage_location }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            ref: ${{ env.CLIENT_VERSION }}

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore SUI.Client.Watcher

        - name: Build
          run: dotnet build SUI.Client.Watcher --configuration Release --output ./output

        - name: Publish
          run: dotnet publish SUI.Client.Watcher --configuration Release --output ./output

        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ env.AZURE_CLIENT_ID }}
            tenant-id: ${{ env.AZURE_TENANT_ID }}
            subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

        - name: Upload to Blob Storage
          run:
            az storage blob upload-batch \
                --destination ${{ env.BLOB_STORAGE_LOCATION }} \
                --source ./output \
                --pattern "*.dll" \
                --pattern "*.exe"