name: Azure Infra Deployment

on:
  push:
    branches:
    - main
    paths:
    - 'src/app-host/infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for deployment
        default: 'Integration'
        type: choice
        options:
          - 'Integration'
      what_if:
        description: Run bicep what-if to check for changes
        default: true
        type: boolean
      version:
        description: The version of the infrastructure to provision (defaults to branch)
        type: string
        required: false
      environment_prefix:
        description: The prefix for the environment
        default: 's215d01'
        type: string
      enable_audit_logging:
        description: Enabling will provision the audit logging infrastructure
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      AZURE_ENV_NAME: ${{ inputs.environment }}
      AZURE_ENV_PREFIX: ${{ inputs.environment_prefix }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      INFRA_VERSION: ${{ inputs.version }}
      AZURE_MONITORING_ACTION_GROUP_EMAIL: ${{ secrets.AZURE_MONITORING_ACTION_GROUP_EMAIL }}
      AZURE_CONTAINER_APP_MANAGED_ENVIRONMENT_NUMBER: ${{ vars.AZURE_CONTAINER_APP_MANAGED_ENVIRONMENT_NUMBER }}
      AZURE_CONTAINER_APP_VNET: ${{ secrets.AZURE_CONTAINER_APP_VNET }}
      AZURE_CONTAINER_APP_ENV_SUBNET: ${{ secrets.AZURE_CONTAINER_APP_ENV_SUBNET }}
      FeatureToggles__EnableAuditLogging: ${{ inputs.enable_audit_logging || 'false' }}
      AZURE_ENABLE_AUDIT_LOGGING: ${{ inputs.enable_audit_logging || 'false' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Get latest tag if no version provided'
        id: get_latest_tag
        run: |
          if [[ -z "${{ env.INFRA_VERSION }}" ]]; then
            git fetch --tags
            LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest tag is: $LATEST_TAG"
            echo "infra_version=$LATEST_TAG" >> $GITHUB_ENV
          else
            echo "Using provided version: ${{ env.INFRA_VERSION }}"
            echo "infra_version=${{ env.INFRA_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Checkout (version)
        uses: actions/checkout@v4
        with:
          ref: ${{ env.infra_version }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire
        
      - name: Ensure Azure CLI is installed
        run: |
          if ! command -v az &> /dev/null; then
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

      - name: Log in with Azure (Federated Credentials)
        if: ${{ env.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID"
        shell: pwsh
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        
      - name: Run Bicep What-If
        if: ${{ inputs.what_if == true }}
        uses: Azure/deployment-what-if-action@v1.0.0
        with:
          subscription: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          templateFile: src/app-host/infra/main.bicep
#          parametersFile: "app-host/infra/main.parameters.json"
          additionalParameters: environmentName="${{ env.AZURE_ENV_NAME }}" environmentPrefix="${{ env.AZURE_ENV_PREFIX }}" location="${{ env.AZURE_LOCATION }}" monitoringActionGroupEmail="${{ env.AZURE_MONITORING_ACTION_GROUP_EMAIL }}" containerAppManagedEnvironmentNumber="${{ env.AZURE_CONTAINER_APP_MANAGED_ENVIRONMENT_NUMBER }}" containerAppVnet="${{ env.AZURE_CONTAINER_APP_VNET }}" containerAppEnvSubnet="${{ env.AZURE_CONTAINER_APP_ENV_SUBNET }}" enableAuditLogging="${{ env.FeatureToggles__EnableAuditLogging }}" 

      - name: Provision Infrastructure
        if: ${{ inputs.what_if == false }}
        run: azd provision --no-prompt --environment ${{ env.AZURE_ENV_NAME }}
        working-directory: src/app-host
