name: Smoke Test Deployed Apps

on:
  workflow_dispatch:
    inputs:
      virtual_machine_name:
        description: "Virtual Machine Name"
        required: true
        default: "s215d01-integration-vm-01"
      after_workflow:
        description: "Trigger specific smoke test workflow"
        type: choice
        required: true
        default: "Azure App Deployment"
        options:
          - "Azure App Deployment"
          - "Build and Upload Client Watcher"
          - "Build and Upload DBS Response Logger Watcher"

  workflow_run:
    workflows:
      [
        "Azure App Deployment",
        "Build and Upload Client Watcher",
        "Build and Upload DBS Response Logger Watcher",
      ]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  env_setup:
    runs-on: ubuntu-latest
    outputs:
      triggered_workflow: ${{ steps.detect_workflow.outputs.triggered_workflow }}
      client_version: ${{ steps.env-setup.outputs.client_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Determine triggering upstream workflow
        id: detect_workflow
        run: |
          if [ "${{ github.event.inputs.after_workflow }}" != "" ]; then
            echo "triggered_workflow=${{ github.event.inputs.after_workflow }}" >> $GITHUB_OUTPUT
          else
            echo "triggered_workflow=${{ github.event.workflow.name || 'Azure App Deployment' }}" >> $GITHUB_OUTPUT
          fi
      - name: Environment Setup
        id: env-setup
        uses: ./.github/actions/env-setup

  dbs_smoketest:
    needs: env_setup
    name: Smoke Test DBS Response Logger
    if: (needs.env_setup.outputs.triggered_workflow == 'Build and Upload DBS Response Logger Watcher')
    uses: ./.github/workflows/gh-smoke-test-executer.yml
    with:
      smoke_test_type: dbs_batch_search
      azure_location: westeurope
      version: ${{ needs.env_setup.outputs.client_version }}
      vm_name: ${{ inputs.virtual_machine_name || 's215d01-integration-vm-01' }}
    secrets:
      sui_server_url: ${{ secrets.AZURE_SUI_SERVER_URL }}
      azure_sub_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}

  client_smoketest:
    needs: env_setup
    name: Smoke Test SUI Client
    if: (needs.env_setup.outputs.triggered_workflow == 'Azure App Deployment' || needs.env_setup.outputs.triggered_workflow == 'Build and Upload Client Watcher')
    uses: ./.github/workflows/gh-smoke-test-executer.yml
    with:
      smoke_test_type: client_batch_search
      use_small_dataset: true
      azure_location: westeurope
      version: ${{ needs.env_setup.outputs.client_version }}
      vm_name: ${{ inputs.virtual_machine_name || 's215d01-integration-vm-01' }}
    secrets:
      sui_server_url: ${{ secrets.AZURE_SUI_SERVER_URL }}
      azure_sub_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
