name: Smoke Test Deployed Apps

on:
  workflow_dispatch:
     inputs:
       blob_storage_location:
         description: 'Blob storage location'
         required: true
         default: 's215d01-integration-container-01'
       storage_account:
         description: 'Storage account'
         required: true
         default: 's215d01integrationsa01'
       virtual_machine_name:
         description: 'Virtual Machine Name'
         required: true
         default: 's215d01-integration-vm-01'
       environment:
         description: 'Environment'
         required: true
         default: 'Integration'
       after_workflow:
         description: 'Trigger specific smoke test workflow'
         type: choice
         required: true
         default: 'Azure App Deployment'
         options:
           - "Azure App Deployment"
           - "Build and Upload Client Watcher"
           - "Build and Upload DBS Response Logger Watcher"
         
  workflow_run:
    workflows: ["Azure App Deployment", "Build and Upload Client Watcher", "Build and Upload DBS Response Logger Watcher"]
    types:
      - completed
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 3:00 AM UTC

permissions:
  id-token: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        env: 
            AZURE_ENV_NAME: ${{ inputs.environment || 'Integration' }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            AZURE_LOCATION: "westeurope"
            AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

        steps:
        - name: Determine triggering upstream workflow
          id: detect_workflow
          run: |
            if [ "${{ github.event.inputs.after_workflow }}" != "" ]; then
              echo "triggered_workflow=${{ github.event.inputs.after_workflow }}" >> $GITHUB_ENV
            elif [ "${{ github.event_name == 'schedule' }}" == "true" ]; then
              echo "cron_run=true" >> $GITHUB_ENV
            else
              echo "triggered_workflow=${{ github.event.workflow.name || 'Azure App Deployment' }}" >> $GITHUB_ENV
            fi

        - name: Checkout
          uses: actions/checkout@v4

        - name: Use version inputted or find latest tag
          id: check-version
          run: |
            if [ -z "${{ github.event.inputs.version }}" ]; then
              echo "No input version provided. Fetching latest tag."
              git fetch --tags
              latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
              echo "Latest tag: $latest_tag"
              echo "CLIENT_VERSION=$latest_tag" >> $GITHUB_ENV
            else
              echo "Using input version: ${{ github.event.inputs.version }}"
              echo "CLIENT_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
            fi

        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ env.CLIENT_VERSION }}

        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ env.AZURE_CLIENT_ID }}
            tenant-id: ${{ env.AZURE_TENANT_ID }}
            subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

        - name: Set Azure Subscription
          run: |
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Read txt file contents
          id: dbs_file
          run: |
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "txt<<${EOF}" >> $GITHUB_OUTPUT
            cat ./tests/E2E.Tests/Resources/Smoke/dbs_batch_search_responses.txt >> $GITHUB_OUTPUT
            echo "${EOF}" >> $GITHUB_OUTPUT

        - name: show contents of csv file
          run: echo "${{ steps.dbs_file.outputs.txt }}" 
              
        - name: Read csv file contents
          id: csv_file
          run: |
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "csv<<${EOF}" >> $GITHUB_OUTPUT
            cat ./tests/E2E.Tests/Resources/Smoke/sui_batch_search_queries.csv >> $GITHUB_OUTPUT
            echo "${EOF}" >> $GITHUB_OUTPUT

        - name: show contents of csv file
          run: echo "${{ steps.csv_file.outputs.csv }}"      

        - name: Smoke Test DBS Response Logger (.exe)
          if: ((env.triggered_workflow == 'Build and Upload DBS Response Logger Watcher') || (env.cron_run == 'true'))
          run: |
            az vm run-command invoke --debug \
              --command-id RunPowerShellScript \
              --name ${{ secrets.VM_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --script '
            
              EndpointSuffix=core.windows.net"
              $destinationPath = "C:\Users\AzCopy\unprocessed\dbs_batch_search_responses.txt"
            
              # Create Directory if does not exist
              New-Item -ItemType Directory -Path "C:\Users\AzCopy\unprocessed"

              # Create file and output contents
              $fileContent = @"
              ${{ steps.dbs_file.outputs.txt }}
              "@
              $fileContent | Out-File -FilePath $destinationPath -Encoding utf8
            
              cd C:\Users\AzCopy
            
              # Execute Smoke Test
              $logContent = .\dbsc.exe $destinationPath
            
              # assert smoke test was successful
              if ($logContent -match "The DBS results file has 7 records, batch search resulted")
              {
                Write-Output "Smoke Test Passed"
                exit 0 # Exit with a non-zero status code
              }
              else
              {
                Write-Error "Smoke Test Failed"
                exit 1 # Exit with a zero status code
              }
              '
            
        - name: Smoke Test SUI Client (.exe)
          if: ((env.triggered_workflow == 'Azure App Deployment' || env.triggered_workflow == 'Build and Upload Client Watcher') || (env.cron_run == 'true'))
          run: |
            az vm run-command invoke --debug \
              --command-id RunPowerShellScript \
              --name ${{ secrets.VM_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --script '
            
              EndpointSuffix=core.windows.net"
              $destinationPath = "C:\Users\AzCopy\unprocessed\sui_batch_search_queries.csv"
            
              # Create Directory if does not exist
              New-Item -ItemType Directory -Path "C:\Users\AzCopy\unprocessed"

              # Create file and output contents
              $fileContent = @"
              ${{ steps.csv_file.outputs.csv }}
              "@

              $fileContent | Out-File -FilePath $destinationPath -Encoding utf8
              get-content $destinationPath
              cd C:\Users\AzCopy
            
              $json_data = @(
                [PSCustomObject]@{
                  MatchApiBaseAddress = "${{ secrets.AZURE_SUI_SERVER_URL }}"
                }
              )
  
              $json_data | ConvertTo-Json | Out-File -FilePath ".\appsettings.json"

              # Execute Smoke Test
              $logContent = .\suic.exe $destinationPath
            
              # assert smoke test was successful
              if ($logContent -match "File processed; output=SUI.Client.Core.ProcessCsvFileResult")
              {
                Write-Output "Smoke Test Passed"
                exit 0 # Exit with a non-zero status code
              }
              else
              {
                Write-Error "Smoke Test Failed"
                exit 1 # Exit with a zero status code
              }
              '