name: Bump version
on:
  push:
    branches:
      - bugfix/sui-67/test-tags
env:
  MAJOR_MINOR_VERSION: 0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create new tag
        env:
          MAJOR_MINOR_VERSION: ${{ env.MAJOR_MINOR_VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a v${MAJOR_MINOR_VERSION}.${{ github.run_number }} -m "Version v${MAJOR_MINOR_VERSION}.${{ github.run_number }}"
          git push origin v${MAJOR_MINOR_VERSION}.${{ github.run_number }}